// frontend-angular/src/app/components/change-password-modal/change-password-modal.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { environment } from '../../../environments/environment';

@Component({
  selector: 'app-change-password-modal',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './change-password-modal.component.html',
})
export class ChangePasswordModalComponent {
  @Input()  token!:  string;
  @Output() closed = new EventEmitter<void>();

  current = '';
  next    = '';
  confirm = '';
  error   = '';
  info    = '';
  loading = false;

  closeIfBackdrop(e: MouseEvent): void {
    if (e.target === e.currentTarget) this.closed.emit();
  }

  async handleSubmit(): Promise<void> {
    this.error = ''; this.info = '';
    if (!this.current)            { this.error = 'Enter your current password'; return; }
    if (this.next.length < 6)     { this.error = 'New password must be at least 6 characters'; return; }
    if (this.next !== this.confirm) { this.error = 'Passwords do not match'; return; }
    this.loading = true;
    try {
      const res  = await fetch(`${environment.serverUrl}/auth/password`, {
        method:  'PATCH',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${this.token}` },
        body:    JSON.stringify({ currentPassword: this.current, newPassword: this.next }),
      });
      const body = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(body?.message ?? 'Failed to update password');
      this.info = 'Password updated successfully!';
      setTimeout(() => this.closed.emit(), 1200);
    } catch (e: unknown) {
      this.error = (e instanceof Error ? e.message : null) ?? 'Something went wrong.';
    } finally {
      this.loading = false;
    }
  }
}

<div (click)="closeIfBackdrop($event)"
     style="position:fixed;inset:0;background:rgba(0,0,0,0.6);display:flex;align-items:center;justify-content:center;z-index:100">
  <div style="background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:1.5rem;width:min(380px,92vw);display:flex;flex-direction:column;gap:1rem">

    <div style="display:flex;justify-content:space-between;align-items:center">
      <div style="font-family:var(--display);font-weight:800;font-size:1rem;color:var(--text)">Change Password</div>
      <button (click)="closed.emit()" style="background:none;border:none;color:var(--text-dim);font-size:1.2rem;cursor:pointer">✕</button>
    </div>

    <div>
      <div style="font-size:0.68rem;letter-spacing:0.1em;text-transform:uppercase;color:var(--text-dim);margin-bottom:0.3rem">Current password</div>
      <input type="password" [(ngModel)]="current" autofocus (keydown.enter)="handleSubmit()"
             style="width:100%;padding:0.65rem 0.9rem;background:var(--bg);border:1px solid var(--border);border-radius:6px;color:var(--text);font-family:var(--mono);font-size:0.9rem;outline:none;box-sizing:border-box" />
    </div>

    <div>
      <div style="font-size:0.68rem;letter-spacing:0.1em;text-transform:uppercase;color:var(--text-dim);margin-bottom:0.3rem">New password</div>
      <input type="password" [(ngModel)]="next" placeholder="Min. 6 characters" (keydown.enter)="handleSubmit()"
             style="width:100%;padding:0.65rem 0.9rem;background:var(--bg);border:1px solid var(--border);border-radius:6px;color:var(--text);font-family:var(--mono);font-size:0.9rem;outline:none;box-sizing:border-box" />
    </div>

    <div>
      <div style="font-size:0.68rem;letter-spacing:0.1em;text-transform:uppercase;color:var(--text-dim);margin-bottom:0.3rem">Confirm new password</div>
      <input type="password" [(ngModel)]="confirm" (keydown.enter)="handleSubmit()"
             style="width:100%;padding:0.65rem 0.9rem;background:var(--bg);border:1px solid var(--border);border-radius:6px;color:var(--text);font-family:var(--mono);font-size:0.9rem;outline:none;box-sizing:border-box" />
    </div>

    @if (error) { <div style="color:#e55;font-size:0.78rem">{{ error }}</div> }
    @if (info)  { <div style="color:var(--accent);font-size:0.78rem">{{ info }}</div> }

    <button (click)="handleSubmit()" [disabled]="loading"
            [style.opacity]="loading ? 0.7 : 1"
            [style.cursor]="loading ? 'not-allowed' : 'pointer'"
            style="padding:0.7rem;background:var(--accent);color:#000;font-family:var(--display);font-weight:700;font-size:0.88rem;border:none;border-radius:6px">
      {{ loading ? 'Updating…' : 'Update password' }}
    </button>

  </div>
</div>

// frontend/src/components/ChangePasswordModal.tsx
'use client';

import { useState, KeyboardEvent } from 'react';

const SERVER_URL = 'http://localhost:8080';

export default function ChangePasswordModal({
  token,
  onClose,
}: {
  token:   string;
  onClose: () => void;
}) {
  const [current, setCurrent] = useState('');
  const [next,    setNext]    = useState('');
  const [confirm, setConfirm] = useState('');
  const [error,   setError]   = useState('');
  const [info,    setInfo]    = useState('');
  const [loading, setLoading] = useState(false);

  async function handleSubmit() {
    setError(''); setInfo('');
    if (!current)           { setError('Enter your current password'); return; }
    if (next.length < 6)    { setError('New password must be at least 6 characters'); return; }
    if (next !== confirm)   { setError('Passwords do not match'); return; }

    setLoading(true);
    try {
      const res  = await fetch(`${SERVER_URL}/auth/password`, {
        method:  'PATCH',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body:    JSON.stringify({ currentPassword: current, newPassword: next }),
        cache:   'no-store',
      });
      const body = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(body?.message ?? 'Failed to update password');
      setInfo('Password updated successfully!');
      setTimeout(onClose, 1200);
    } catch (e: any) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  }

  function handleKey(e: KeyboardEvent<HTMLInputElement>) {
    if (e.key === 'Enter') handleSubmit();
  }

  const inputStyle: React.CSSProperties = {
    padding: '0.65rem 0.9rem',
    background: 'var(--bg)',
    border: '1px solid var(--border)',
    borderRadius: 6,
    color: 'var(--text)',
    fontFamily: 'var(--mono)',
    fontSize: '0.9rem',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
  };

  const labelStyle: React.CSSProperties = {
    fontSize: '0.68rem',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    color: 'var(--text-dim)',
    marginBottom: '0.3rem',
  };

  return (
    <div
      style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.6)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 100 }}
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 8, padding: '1.5rem', width: 'min(380px,92vw)', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div style={{ fontFamily: 'var(--display)', fontWeight: 800, fontSize: '1rem', color: 'var(--text)' }}>Change Password</div>
          <button onClick={onClose} style={{ background: 'none', border: 'none', color: 'var(--text-dim)', fontSize: '1.2rem', cursor: 'pointer' }}>✕</button>
        </div>

        <div><div style={labelStyle}>Current password</div><input type="password" autoFocus value={current} onChange={(e) => setCurrent(e.target.value)} onKeyDown={handleKey} style={inputStyle} /></div>
        <div><div style={labelStyle}>New password</div><input type="password" value={next} placeholder="Min. 6 characters" onChange={(e) => setNext(e.target.value)} onKeyDown={handleKey} style={inputStyle} /></div>
        <div><div style={labelStyle}>Confirm new password</div><input type="password" value={confirm} onChange={(e) => setConfirm(e.target.value)} onKeyDown={handleKey} style={inputStyle} /></div>

        {error && <div style={{ color: '#e55', fontSize: '0.78rem' }}>{error}</div>}
        {info  && <div style={{ color: 'var(--accent)', fontSize: '0.78rem' }}>{info}</div>}

        <button
          onClick={handleSubmit}
          disabled={loading}
          style={{ padding: '0.7rem', background: 'var(--accent)', color: '#000', fontFamily: 'var(--display)', fontWeight: 700, fontSize: '0.88rem', border: 'none', borderRadius: 6, cursor: loading ? 'not-allowed' : 'pointer', opacity: loading ? 0.7 : 1 }}
        >
          {loading ? 'Updating…' : 'Update password'}
        </button>
      </div>
    </div>
  );
}
