// frontend-angular/src/app/components/message-list/message-list.component.ts
import {
  Component, Input, OnChanges, ViewChild,
  ElementRef, AfterViewChecked,
} from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { MessageItem } from '../../models/chat.models';

@Component({
  selector: 'app-message-list',
  standalone: true,
  templateUrl: './message-list.component.html',
})
export class MessageListComponent implements OnChanges, AfterViewChecked {
  @Input() messages:    MessageItem[] = [];
  @Input() currentUser = '';

  @ViewChild('bottom') bottomRef!: ElementRef<HTMLDivElement>;

  private shouldScroll = false;

  constructor(private sanitizer: DomSanitizer) {}

  ngOnChanges(): void {
    this.shouldScroll = true;
  }

  ngAfterViewChecked(): void {
    if (this.shouldScroll) {
      this.bottomRef?.nativeElement.scrollIntoView({ behavior: 'smooth' });
      this.shouldScroll = false;
    }
  }

  formatTime(ts: number): string {
    return new Date(ts).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  }

  renderText(text: string, currentUser: string): SafeHtml {
    const parts = text.split(/(@[\w-]{1,24})/g);
    const html = parts.map(part => {
      if (part.startsWith('@')) {
        const name = part.slice(1);
        const isMe = name === currentUser;
        const color = isMe ? '#ff9944' : 'var(--accent)';
        const bg    = isMe ? '#ff994415' : '#00e5a010';
        return `<span style="font-weight:700;color:${color};background:${bg};border-radius:3px;padding:0 2px">${this.esc(part)}</span>`;
      }
      return this.esc(part);
    }).join('');
    return this.sanitizer.bypassSecurityTrustHtml(html);
  }

  private esc(s: string): string {
    return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }

  isGrouped(i: number): boolean {
    const prev = this.messages[i - 1];
    const cur  = this.messages[i];
    return !!(prev && prev.kind === 'chat' && cur.kind === 'chat' && prev.username === cur.username);
  }

  isMentioned(msg: MessageItem): boolean {
    return msg.kind === 'chat' && !!(msg.mentions?.includes(this.currentUser));
  }
}

<div style="flex:1;overflow-y:auto;padding:1.25rem 1.5rem;display:flex;flex-direction:column;gap:0.15rem">
  @for (msg of messages; track msg.id; let i = $index) {
    @if (msg.kind === 'system') {
      <div style="align-self:center;font-size:0.7rem;color:var(--muted);padding:0.2rem 0.8rem;border-radius:999px;border:1px solid var(--border);margin:0.5rem 0">
        {{ msg.text }}
      </div>
    } @else {
      <div [style.align-items]="msg.username === currentUser ? 'flex-end' : 'flex-start'"
           [style.align-self]="msg.username === currentUser ? 'flex-end' : 'flex-start'"
           [style.margin-top]="isGrouped(i) ? '0' : '0.75rem'"
           style="display:flex;flex-direction:column;max-width:72%">
        @if (!isGrouped(i)) {
          <div [style.color]="msg.username === currentUser ? 'var(--accent)' : 'var(--muted)'"
               [style.opacity]="msg.username === currentUser ? 0.7 : 1"
               style="font-size:0.65rem;margin-bottom:0.25rem;padding:0 0.5rem">
            {{ msg.username }} · {{ formatTime(msg.timestamp) }}
          </div>
        }
        <div [style.background]="isMentioned(msg) ? '#ff994410' : msg.username === currentUser ? '#00e5a018' : 'var(--surface)'"
             [style.border]="isMentioned(msg) ? '1px solid #ff994450' : msg.username === currentUser ? '1px solid #00e5a035' : '1px solid var(--border)'"
             [style.border-bottom-right-radius]="msg.username === currentUser ? '2px' : '6px'"
             [style.border-bottom-left-radius]="msg.username === currentUser ? '6px' : '2px'"
             style="padding:0.6rem 0.9rem;border-radius:6px;font-size:0.88rem;line-height:1.55;word-break:break-word;white-space:pre-wrap">
          <span [innerHTML]="renderText(msg.text, currentUser)"></span>
          @if (isMentioned(msg)) {
            <span style="margin-left:6px;font-size:0.65rem;color:#ff9944;font-weight:700">◀ you</span>
          }
        </div>
      </div>
    }
  }
  <div #bottom></div>
</div>

// frontend/src/components/MessageList.tsx
'use client';

import { useEffect, useRef } from 'react';
import { MessageItem } from '@/types/chat';

function formatTime(ts: number): string {
  return new Date(ts).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
}

/** Render text with @mentions highlighted */
function renderText(text: string, currentUser: string) {
  const parts = text.split(/(@[\w-]{1,24})/g);
  return parts.map((part, i) => {
    if (part.startsWith('@')) {
      const name  = part.slice(1);
      const isMe  = name === currentUser;
      return (
        <span key={i} style={{ fontWeight: 700, color: isMe ? '#ff9944' : 'var(--accent)', background: isMe ? '#ff994415' : 'var(--accent)10', borderRadius: 3, padding: '0 2px' }}>
          {part}
        </span>
      );
    }
    return <span key={i}>{part}</span>;
  });
}

export default function MessageList({
  messages,
  currentUser,
}: {
  messages:    MessageItem[];
  currentUser: string;
}) {
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  return (
    <div style={{ flex: 1, overflowY: 'auto', padding: '1.25rem 1.5rem', display: 'flex', flexDirection: 'column', gap: '0.15rem' }}>
      {messages.map((msg, i) => {
        if (msg.kind === 'system') {
          return (
            <div key={msg.id} style={{ alignSelf: 'center', fontSize: '0.7rem', color: 'var(--muted)', padding: '0.2rem 0.8rem', borderRadius: '999px', border: '1px solid var(--border)', margin: '0.5rem 0' }}>
              {msg.text}
            </div>
          );
        }

        const isSelf     = msg.username === currentUser;
        const isMentioned = msg.mentions?.includes(currentUser);
        const prev        = messages[i - 1];
        const isGrouped   = prev && prev.kind === 'chat' && prev.username === msg.username;

        return (
          <div
            key={msg.id}
            style={{
              display: 'flex', flexDirection: 'column',
              alignItems:  isSelf ? 'flex-end' : 'flex-start',
              alignSelf:   isSelf ? 'flex-end' : 'flex-start',
              maxWidth:    '72%',
              marginTop:   isGrouped ? 0 : '0.75rem',
            }}
          >
            {!isGrouped && (
              <div style={{ fontSize: '0.65rem', color: isSelf ? 'var(--accent)' : 'var(--muted)', opacity: isSelf ? 0.7 : 1, marginBottom: '0.25rem', padding: '0 0.5rem' }}>
                {msg.username} · {formatTime(msg.timestamp)}
              </div>
            )}
            <div
              style={{
                padding: '0.6rem 0.9rem', borderRadius: '6px', fontSize: '0.88rem', lineHeight: 1.55, wordBreak: 'break-word', whiteSpace: 'pre-wrap',
                background: isMentioned ? '#ff994410' : isSelf ? '#00e5a018' : 'var(--surface)',
                border: isMentioned
                  ? '1px solid #ff994450'
                  : isSelf ? '1px solid #00e5a035' : '1px solid var(--border)',
                borderBottomRightRadius: isSelf ? 2 : 6,
                borderBottomLeftRadius:  isSelf ? 6 : 2,
              }}
            >
              {renderText(msg.text, currentUser)}
              {isMentioned && (
                <span style={{ marginLeft: 6, fontSize: '0.65rem', color: '#ff9944', fontWeight: 700 }}>◀ you</span>
              )}
            </div>
          </div>
        );
      })}
      <div ref={bottomRef} />
    </div>
  );
}
