// frontend/src/components/DirectMessagePanel.tsx
'use client';

import { useState, useRef, useEffect, KeyboardEvent } from 'react';
import { DmMessage } from '@/types/chat';

function formatTime(ts: number) {
  return new Date(ts).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
}

export default function DirectMessagePanel({
  partner,
  currentUser,
  messages,
  onSend,
  onClose,
}: {
  partner:     string;
  currentUser: string;
  messages:    DmMessage[];
  onSend:      (text: string) => void;
  onClose:     () => void;
}) {
  const [draft,  setDraft]  = useState('');
  const bottomRef           = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  function handleSend() {
    if (!draft.trim()) return;
    onSend(draft.trim());
    setDraft('');
  }

  function handleKey(e: KeyboardEvent<HTMLTextAreaElement>) {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handleSend(); }
  }

  return (
    <>
      {/* Desktop: floating panel bottom-right */}
      <div className="dm-panel-desktop" style={{
        position:       'fixed',
        bottom:         '5rem',
        right:          '1.5rem',
        width:          'min(380px, 92vw)',
        height:         460,
        background:     'var(--surface)',
        border:         '1px solid var(--border)',
        borderRadius:   10,
        display:        'flex',
        flexDirection:  'column',
        boxShadow:      '0 8px 40px rgba(0,0,0,0.5)',
        zIndex:         150,
      }}>
        <DmPanelContent
          partner={partner}
          currentUser={currentUser}
          messages={messages}
          draft={draft}
          setDraft={setDraft}
          onSend={handleSend}
          onClose={onClose}
          onKey={handleKey}
          bottomRef={bottomRef}
        />
      </div>

      {/* Mobile: full-screen overlay */}
      <div className="dm-panel-mobile" style={{
        position:       'fixed',
        inset:          0,
        background:     'var(--bg)',
        display:        'flex',
        flexDirection:  'column',
        zIndex:         250,
      }}>
        <DmPanelContent
          partner={partner}
          currentUser={currentUser}
          messages={messages}
          draft={draft}
          setDraft={setDraft}
          onSend={handleSend}
          onClose={onClose}
          onKey={handleKey}
          bottomRef={bottomRef}
        />
      </div>
    </>
  );
}

function DmPanelContent({
  partner, currentUser, messages, draft, setDraft,
  onSend, onClose, onKey, bottomRef,
}: {
  partner:     string;
  currentUser: string;
  messages:    DmMessage[];
  draft:       string;
  setDraft:    (v: string) => void;
  onSend:      () => void;
  onClose:     () => void;
  onKey:       (e: KeyboardEvent<HTMLTextAreaElement>) => void;
  bottomRef:   React.RefObject<HTMLDivElement>;
}) {
  return (
    <>
      {/* Header */}
      <div style={{
        display: 'flex', alignItems: 'center',
        padding: '0.75rem 1rem', borderBottom: '1px solid var(--border)', gap: '0.5rem',
        flexShrink: 0,
      }}>
        <div style={{ width: 8, height: 8, borderRadius: '50%', background: 'var(--accent)', flexShrink: 0 }} />
        <span style={{ fontFamily: 'var(--display)', fontWeight: 700, fontSize: '0.9rem', flex: 1, color: 'var(--text)' }}>
          @{partner}
        </span>
        <button
          onClick={onClose}
          title="Hide conversation"
          style={{
            display: 'flex', alignItems: 'center', gap: '0.3rem',
            background: 'var(--bg)', border: '1px solid var(--border)',
            color: 'var(--text-dim)', cursor: 'pointer',
            borderRadius: 5, padding: '0.2rem 0.55rem',
            fontSize: '0.72rem', fontFamily: 'var(--display)', fontWeight: 700,
          }}
        >
          <span style={{ fontSize: '0.7rem' }}>✕</span> Hide
        </button>
      </div>

      {/* Messages */}
      <div style={{
        flex: 1, overflowY: 'auto', padding: '0.75rem 1rem',
        display: 'flex', flexDirection: 'column', gap: '0.4rem',
      }}>
        {messages.length === 0 && (
          <div style={{ color: 'var(--text-dim)', fontSize: '0.8rem', textAlign: 'center', marginTop: '2rem' }}>
            Start your conversation with @{partner}
          </div>
        )}
        {messages.map(msg => {
          const isSelf = msg.from === currentUser;
          return (
            <div key={msg.id} style={{
              display: 'flex', flexDirection: 'column',
              alignItems: isSelf ? 'flex-end' : 'flex-start',
              alignSelf:  isSelf ? 'flex-end' : 'flex-start',
              maxWidth:   '85%',
            }}>
              <div style={{
                padding: '0.5rem 0.8rem', borderRadius: 6,
                fontSize: '0.83rem', lineHeight: 1.5,
                wordBreak: 'break-word', whiteSpace: 'pre-wrap',
                background: isSelf ? '#00e5a018' : 'var(--bg)',
                border:     isSelf ? '1px solid #00e5a035' : '1px solid var(--border)',
                borderBottomRightRadius: isSelf ? 2 : 6,
                borderBottomLeftRadius:  isSelf ? 6 : 2,
              }}>
                {msg.text}
              </div>
              <div style={{ fontSize: '0.62rem', color: 'var(--muted)', marginTop: '0.15rem', padding: '0 0.3rem' }}>
                {formatTime(msg.timestamp)}
              </div>
            </div>
          );
        })}
        <div ref={bottomRef} />
      </div>

      {/* Input */}
      <div style={{
        padding: '0.6rem 0.75rem', borderTop: '1px solid var(--border)',
        display: 'flex', gap: '0.5rem', alignItems: 'flex-end', flexShrink: 0,
      }}>
        <textarea
          value={draft}
          onChange={e => setDraft(e.target.value)}
          onKeyDown={onKey}
          placeholder={`Message @${partner}…`}
          rows={1}
          style={{
            flex: 1, resize: 'none', minHeight: 36, maxHeight: 100,
            padding: '0.5rem 0.75rem', background: 'var(--bg)',
            border: '1px solid var(--border)', borderRadius: 6,
            color: 'var(--text)', fontFamily: 'var(--mono)', fontSize: '0.82rem',
            outline: 'none', lineHeight: 1.4,
          }}
        />
        <button
          onClick={onSend}
          disabled={!draft.trim()}
          style={{
            height: 36, padding: '0 0.9rem', background: 'var(--accent)', color: '#000',
            fontFamily: 'var(--display)', fontWeight: 700, fontSize: '0.78rem',
            border: 'none', borderRadius: 6,
            cursor: draft.trim() ? 'pointer' : 'not-allowed',
            opacity: draft.trim() ? 1 : 0.35, flexShrink: 0,
          }}
        >
          Send
        </button>
      </div>
    </>
  );
}

// frontend-angular/src/app/components/direct-message-panel/direct-message-panel.component.ts
import {
  Component, Input, OnChanges, Output, EventEmitter,
  ViewChild, ElementRef, AfterViewChecked,
} from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { DmMessage } from '../../models/chat.models';

@Component({
  selector: 'app-direct-message-panel',
  standalone: true,
  imports: [NgTemplateOutlet, FormsModule],
  templateUrl: './direct-message-panel.component.html',
})
export class DirectMessagePanelComponent implements OnChanges, AfterViewChecked {
  @Input()  partner!:     string;
  @Input()  currentUser!: string;
  @Input()  messages:     DmMessage[] = [];
  @Output() send         = new EventEmitter<string>();
  @Output() closed       = new EventEmitter<void>();

  @ViewChild('bottom') bottomRef!: ElementRef<HTMLDivElement>;

  draft         = '';
  private scroll = false;

  ngOnChanges(): void { this.scroll = true; }

  ngAfterViewChecked(): void {
    if (this.scroll) {
      this.bottomRef?.nativeElement.scrollIntoView({ behavior: 'smooth' });
      this.scroll = false;
    }
  }

  handleSend(): void {
    if (!this.draft.trim()) return;
    this.send.emit(this.draft.trim());
    this.draft = '';
  }

  handleKey(e: KeyboardEvent): void {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); this.handleSend(); }
  }

  formatTime(ts: number): string {
    return new Date(ts).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  }
}

<!-- Desktop: floating bottom-right panel -->
<div class="dm-panel-desktop"
     style="position:fixed;bottom:5rem;right:1.5rem;width:min(380px,92vw);height:460px;background:var(--surface);border:1px solid var(--border);border-radius:10px;display:flex;flex-direction:column;box-shadow:0 8px 40px rgba(0,0,0,0.5);z-index:150">
  <ng-container *ngTemplateOutlet="content"></ng-container>
</div>

<!-- Mobile: full-screen overlay -->
<div class="dm-panel-mobile"
     style="position:fixed;inset:0;background:var(--bg);display:flex;flex-direction:column;z-index:250">
  <ng-container *ngTemplateOutlet="content"></ng-container>
</div>

<ng-template #content>
  <!-- Header -->
  <div style="display:flex;align-items:center;padding:0.75rem 1rem;border-bottom:1px solid var(--border);gap:0.5rem;flex-shrink:0">
    <div style="width:8px;height:8px;border-radius:50%;background:var(--accent);flex-shrink:0"></div>
    <span style="font-family:var(--display);font-weight:700;font-size:0.9rem;flex:1;color:var(--text)">&#64;{{ partner }}</span>
    <button (click)="closed.emit()" title="Hide conversation"
            style="display:flex;align-items:center;gap:0.3rem;background:var(--bg);border:1px solid var(--border);color:var(--text-dim);cursor:pointer;border-radius:5px;padding:0.2rem 0.55rem;font-size:0.72rem;font-family:var(--display);font-weight:700">
      <span style="font-size:0.7rem">✕</span> Hide
    </button>
  </div>

  <!-- Messages -->
  <div style="flex:1;overflow-y:auto;padding:0.75rem 1rem;display:flex;flex-direction:column;gap:0.4rem">
    @if (messages.length === 0) {
      <div style="color:var(--text-dim);font-size:0.8rem;text-align:center;margin-top:2rem">
        Start your conversation with &#64;{{ partner }}
      </div>
    }
    @for (msg of messages; track msg.id) {
      <div [style.align-items]="msg.from === currentUser ? 'flex-end' : 'flex-start'"
           [style.align-self]="msg.from === currentUser ? 'flex-end' : 'flex-start'"
           style="display:flex;flex-direction:column;max-width:85%">
        <div [style.background]="msg.from === currentUser ? '#00e5a018' : 'var(--bg)'"
             [style.border]="msg.from === currentUser ? '1px solid #00e5a035' : '1px solid var(--border)'"
             [style.border-bottom-right-radius]="msg.from === currentUser ? '2px' : '6px'"
             [style.border-bottom-left-radius]="msg.from === currentUser ? '6px' : '2px'"
             style="padding:0.5rem 0.8rem;border-radius:6px;font-size:0.83rem;line-height:1.5;word-break:break-word;white-space:pre-wrap">
          {{ msg.text }}
        </div>
        <div style="font-size:0.62rem;color:var(--muted);margin-top:0.15rem;padding:0 0.3rem">
          {{ formatTime(msg.timestamp) }}
        </div>
      </div>
    }
    <div #bottom></div>
  </div>

  <!-- Input -->
  <div style="padding:0.6rem 0.75rem;border-top:1px solid var(--border);display:flex;gap:0.5rem;align-items:flex-end;flex-shrink:0">
    <textarea [(ngModel)]="draft" (keydown)="handleKey($event)"
              [placeholder]="'Message @' + partner + '…'"
              rows="1"
              style="flex:1;resize:none;min-height:36px;max-height:100px;padding:0.5rem 0.75rem;background:var(--bg);border:1px solid var(--border);border-radius:6px;color:var(--text);font-family:var(--mono);font-size:0.82rem;outline:none;line-height:1.4"></textarea>
    <button (click)="handleSend()" [disabled]="!draft.trim()"
            [style.opacity]="draft.trim() ? 1 : 0.35"
            [style.cursor]="draft.trim() ? 'pointer' : 'not-allowed'"
            style="height:36px;padding:0 0.9rem;background:var(--accent);color:#000;font-family:var(--display);font-weight:700;font-size:0.78rem;border:none;border-radius:6px;flex-shrink:0">
      Send
    </button>
  </div>
</ng-template>
