// frontend/src/app/page.tsx
'use client';

import { useState, useEffect, useCallback, useRef } from 'react';
import LoginScreen, { LoginResult }  from '@/components/LoginScreen';
import Sidebar, { MobileMenuButton } from '@/components/Sidebar';
import MessageList                    from '@/components/MessageList';
import MessageInput                   from '@/components/MessageInput';
import AdminPanel                     from '@/components/AdminPanel';
import ChangePasswordModal            from '@/components/ChangePasswordModal';
import DirectMessagePanel             from '@/components/DirectMessagePanel';
import { useChat }                    from '@/hooks/useChat';
import { Room, MentionNotification }  from '@/types/chat';

import { SERVER_URL } from '@/lib/env';
const SESSION_KEY = 'chatroom_session';

interface Session { token: string; username: string; role: 'user' | 'admin'; }
type Modal = 'none' | 'admin' | 'changePassword';

function loadSession(): Session | null {
  if (typeof window === 'undefined') return null;
  try {
    const raw = sessionStorage.getItem(SESSION_KEY) ?? localStorage.getItem(SESSION_KEY);
    if (!raw) return null;
    const s = JSON.parse(raw) as Session;
    if (!s.token || !s.username) return null;
    return s;
  } catch { return null; }
}

function saveSession(s: Session) {
  const j = JSON.stringify(s);
  localStorage.setItem(SESSION_KEY, j);
  sessionStorage.setItem(SESSION_KEY, j);
}

function clearSession() {
  localStorage.removeItem(SESSION_KEY);
  sessionStorage.removeItem(SESSION_KEY);
}

export default function ChatPage() {
  const [mounted,        setMounted]        = useState(false);
  const [session,        setSession]        = useState<Session | null>(null);
  const [modal,          setModal]          = useState<Modal>('none');
  const [allRooms,       setAllRooms]       = useState<Room[]>([]);
  const [showJoinMenu,   setShowJoinMenu]   = useState(false);
  const [mobileSidebar,  setMobileSidebar]  = useState(false);

  const joinMenuRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const saved = loadSession();
    if (saved) setSession(saved);
    setMounted(true);
  }, []);

  useEffect(() => {
    if (!showJoinMenu) return;
    function handler(e: MouseEvent) {
      if (joinMenuRef.current && !joinMenuRef.current.contains(e.target as Node)) {
        setShowJoinMenu(false);
      }
    }
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [showJoinMenu]);

  const handleAuthError = useCallback(() => {
    clearSession(); setSession(null); setModal('none');
  }, []);

  const {
    messages, users, status, currentRoom, rooms,
    unreadCounts, mentions, presenceStatus,
    dmMessages, dmConversations, dmUnread, activeDm, globalPresence,
    sendMessage, switchRoom, exitRoom, setPresence,
    clearMention, markRoomRead,
    sendDm, openDm, closeDm, closeDmConversation,
    disconnect,
  } = useChat({ token: session?.token ?? '', username: session?.username ?? '', enabled: !!session, onAuthError: handleAuthError });

  const fetchAllRooms = useCallback(async () => {
    if (!session) return;
    try {
      const res = await fetch(`${SERVER_URL}/auth/rooms`, { headers: { Authorization: `Bearer ${session.token}` } });
      if (res.ok) setAllRooms(await res.json());
    } catch {}
  }, [session]);

  useEffect(() => { fetchAllRooms(); }, [fetchAllRooms, rooms]);

  const handleSwitchRoom = useCallback((roomId: number) => {
    markRoomRead(roomId);
    switchRoom(roomId);
  }, [switchRoom, markRoomRead]);

  if (!mounted) return null;

  if (!session) {
    return (
      <LoginScreen onLogin={(result: LoginResult) => {
        saveSession(result); setSession(result); setModal('none');
      }} />
    );
  }

  function handleLogout() { disconnect(); clearSession(); setSession(null); setModal('none'); }

  const memberRoomIds  = new Set(rooms.map(r => r.id));
  const joinableRooms  = allRooms.filter(r => !memberRoomIds.has(r.id) && r.name.toLowerCase() !== 'general');
  const totalUnread    = Object.values(unreadCounts).reduce((a, b) => a + b, 0)
                       + Object.values(dmUnread).reduce((a, b) => a + b, 0);

  return (
    <>
      <div style={{ display: 'flex', flexDirection: 'row', height: '100dvh', overflow: 'hidden' }}>
        <Sidebar
          status={status}
          users={users}
          currentUser={session.username}
          isAdmin={session.role === 'admin'}
          onLogout={handleLogout}
          onAdminPanel={() => setModal('admin')}
          onChangePassword={() => setModal('changePassword')}
          rooms={rooms}
          currentRoom={currentRoom}
          onSwitchRoom={handleSwitchRoom}
          onExitRoom={exitRoom}
          unreadCounts={unreadCounts}
          presenceStatus={presenceStatus}
          onSetPresence={setPresence}
          token={session.token}
          onOpenDm={openDm}
          onCloseDmConversation={closeDmConversation}
          dmConversations={dmConversations}
          dmUnread={dmUnread}
          activeDm={activeDm}
          globalPresence={globalPresence}
          mobileOpen={mobileSidebar}
          onMobileClose={() => setMobileSidebar(false)}
        />

        <main style={{ flex: 1, display: 'flex', flexDirection: 'column', minWidth: 0 }}>
          {/* Header */}
          <div style={{
            padding: '0.75rem 1rem',
            borderBottom: '1px solid var(--border)',
            display: 'flex', alignItems: 'center',
            justifyContent: 'space-between',
            gap: '0.75rem',
            fontSize: '0.8rem', color: 'var(--text-dim)',
          }}>
            {/* Left: hamburger (mobile) + room name */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', minWidth: 0 }}>
              <div className="mobile-only">
                <MobileMenuButton
                  onClick={() => setMobileSidebar(true)}
                  unreadTotal={totalUnread}
                />
              </div>
              <strong style={{
                fontFamily: 'var(--display)', fontSize: '1rem',
                color: 'var(--text)', fontWeight: 700,
                overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
              }}>
                {currentRoom ? `# ${currentRoom.name}` : '# …'}
              </strong>
            </div>

            {/* Right: user count + join room */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', flexShrink: 0 }}>
              <span style={{ display: 'none' }} className="desktop-stat">{users.length} in room</span>
              {joinableRooms.length > 0 && (
                <div ref={joinMenuRef} style={{ position: 'relative' }}>
                  <button
                    onClick={() => setShowJoinMenu(v => !v)}
                    style={{
                      padding: '0.25rem 0.6rem', border: '1px solid var(--border)',
                      borderRadius: 6, fontSize: '0.75rem', cursor: 'pointer',
                      background: showJoinMenu ? 'var(--surface)' : 'transparent',
                      color: 'var(--text-dim)', fontFamily: 'var(--display)',
                      whiteSpace: 'nowrap',
                    }}
                  >
                    + Join room
                  </button>
                  {showJoinMenu && (
                    <div style={{
                      position: 'absolute', right: 0, top: '110%',
                      background: 'var(--surface)', border: '1px solid var(--border)',
                      borderRadius: 6, zIndex: 50, minWidth: 180, padding: '0.5rem',
                    }}>
                      {joinableRooms.map(r => (
                        <button
                          key={r.id}
                          onClick={async () => {
                            const res  = await fetch(`${SERVER_URL}/auth/rooms/${r.id}/join`, { method: 'POST', headers: { Authorization: `Bearer ${session.token}` } });
                            const body = await res.json().catch(() => ({}));
                            setShowJoinMenu(false);
                            alert(body?.message ?? (res.ok ? 'Request sent!' : 'Error'));
                            fetchAllRooms();
                          }}
                          style={{
                            display: 'block', width: '100%', padding: '0.4rem 0.6rem',
                            background: 'none', border: 'none', color: 'var(--text)',
                            fontFamily: 'var(--mono)', fontSize: '0.8rem',
                            cursor: 'pointer', textAlign: 'left', borderRadius: 4,
                          }}
                        >
                          # {r.name}
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>

          <MessageList messages={messages} currentUser={session.username} />
          <MessageInput status={status} onSend={sendMessage} users={users} />
        </main>
      </div>

      {/* DM panel — full screen on mobile, floating on desktop */}
      {activeDm && (
        <DirectMessagePanel
          partner={activeDm}
          currentUser={session.username}
          messages={dmMessages[activeDm] ?? []}
          onSend={text => sendDm(activeDm, text)}
          onClose={closeDm}
        />
      )}

      {/* Mention toasts */}
      {mentions.length > 0 && (
        <div style={{
          position: 'fixed', bottom: '1.5rem', right: '1rem',
          display: 'flex', flexDirection: 'column', gap: '0.5rem',
          zIndex: 200, maxWidth: 'min(320px, calc(100vw - 2rem))',
        }}>
          {mentions.map((m: MentionNotification) => (
            <div key={m.id} style={{
              background: 'var(--surface)', border: '1px solid #ff9944',
              borderRadius: 8, padding: '0.75rem 1rem',
              boxShadow: '0 4px 20px rgba(0,0,0,0.4)', fontSize: '0.82rem',
            }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '0.35rem' }}>
                <span style={{ fontWeight: 700, color: '#ff9944' }}>@mention in #{m.roomName}</span>
                <button onClick={() => clearMention(m.id)} style={{ background: 'none', border: 'none', color: 'var(--muted)', cursor: 'pointer', fontSize: '0.8rem' }}>✕</button>
              </div>
              <div style={{ color: 'var(--text-dim)', marginBottom: '0.4rem' }}>
                <strong style={{ color: 'var(--text)' }}>{m.username}</strong>: {m.text.slice(0, 100)}{m.text.length > 100 ? '…' : ''}
              </div>
              <button
                onClick={() => { handleSwitchRoom(m.roomId); clearMention(m.id); }}
                style={{ fontSize: '0.72rem', padding: '0.2rem 0.6rem', border: '1px solid #ff9944', borderRadius: 4, background: 'none', color: '#ff9944', cursor: 'pointer' }}
              >
                Go to room →
              </button>
            </div>
          ))}
        </div>
      )}

      {modal === 'admin'          && <AdminPanel token={session.token} onClose={() => setModal('none')} />}
      {modal === 'changePassword' && <ChangePasswordModal token={session.token} onClose={() => setModal('none')} />}
    </>
  );
}

// frontend-angular/src/app/app.component.ts
import { Component }    from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
  selector:   'app-root',
  standalone: true,
  imports:    [RouterOutlet],
  template:   '<router-outlet />',
})
export class AppComponent {}

@if (!mounted) {
  <!-- hydration guard — renders nothing until OnInit runs -->
}

@if (mounted && !session) {
  <app-login (loggedIn)="onLoggedIn($event)"></app-login>
}

@if (mounted && session) {
  <div style="display:flex;flex-direction:row;height:100dvh;overflow:hidden">

    <!-- Sidebar -->
    <app-sidebar
      [status]="(status$ | async)!"
      [users]="(users$ | async) ?? []"
      [currentUser]="session.username"
      [isAdmin]="session.role === 'admin'"
      [rooms]="(rooms$ | async) ?? []"
      [currentRoom]="(currentRoom$ | async) ?? null"
      [unreadCounts]="(unreadCounts$ | async) ?? {}"
      [presenceStatus]="(presenceStatus$ | async) ?? 'online'"
      [dmConversations]="(dmConversations$ | async) ?? []"
      [dmUnread]="(dmUnread$ | async) ?? {}"
      [activeDm]="(activeDm$ | async) ?? null"
      [globalPresence]="(globalPresence$ | async) ?? emptyPresenceMap"
      [mobileOpen]="mobileSidebar"
      (logout)="handleLogout()"
      (adminPanel)="modal = 'admin'"
      (changePassword)="modal = 'changePassword'"
      (switchRoom)="handleSwitchRoom($event)"
      (exitRoom)="exitRoom($event)"
      (setPresence)="setPresence($event)"
      (openDm)="openDm($event)"
      (closeDmConvo)="closeDmConvo($event)"
      (mobileClose)="mobileSidebar = false">
    </app-sidebar>

    <!-- Main area -->
    <main style="flex:1;display:flex;flex-direction:column;min-width:0">

      <!-- Header -->
      <div style="padding:0.75rem 1rem;border-bottom:1px solid var(--border);display:flex;align-items:center;justify-content:space-between;gap:0.75rem;font-size:0.8rem;color:var(--text-dim)">
        <div style="display:flex;align-items:center;gap:0.6rem;min-width:0">
          <!-- Mobile hamburger -->
          <button class="mobile-only" (click)="mobileSidebar = true"
                  style="position:relative;background:var(--surface);border:1px solid var(--border);border-radius:6px;padding:0.35rem 0.55rem;cursor:pointer;color:var(--text-dim);font-size:1rem;line-height:1">
            ☰
            @if ((totalUnread$ | async)! > 0) {
              <span style="position:absolute;top:-5px;right:-5px;background:#ff9944;color:#000;border-radius:999px;font-size:0.55rem;font-weight:800;padding:0 4px;min-width:14px;text-align:center;line-height:14px;height:14px">
                {{ (totalUnread$ | async)! > 99 ? '99+' : (totalUnread$ | async) }}
              </span>
            }
          </button>
          <strong style="font-family:var(--display);font-size:1rem;color:var(--text);font-weight:700;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">
            {{ (currentRoom$ | async) ? '# ' + (currentRoom$ | async)!.name : '# …' }}
          </strong>
        </div>

        <div style="display:flex;align-items:center;gap:0.75rem;flex-shrink:0">
          <span class="desktop-stat">{{ (users$ | async)?.length ?? 0 }} in room</span>
          @if (joinableRooms.length > 0) {
            <div #joinMenuRef style="position:relative">
              <button (click)="showJoinMenu = !showJoinMenu"
                      [style.background]="showJoinMenu ? 'var(--surface)' : 'transparent'"
                      style="padding:0.25rem 0.6rem;border:1px solid var(--border);border-radius:6px;font-size:0.75rem;cursor:pointer;color:var(--text-dim);font-family:var(--display);white-space:nowrap">
                + Join room
              </button>
              @if (showJoinMenu) {
                <div style="position:absolute;right:0;top:110%;background:var(--surface);border:1px solid var(--border);border-radius:6px;z-index:50;min-width:180px;padding:0.5rem">
                  @for (r of joinableRooms; track r.id) {
                    <button (click)="joinRoom(r)"
                            style="display:block;width:100%;padding:0.4rem 0.6rem;background:none;border:none;color:var(--text);font-family:var(--mono);font-size:0.8rem;cursor:pointer;text-align:left;border-radius:4px">
                      # {{ r.name }}
                    </button>
                  }
                </div>
              }
            </div>
          }
        </div>
      </div>

      <app-message-list
        [messages]="(messages$ | async) ?? []"
        [currentUser]="session.username">
      </app-message-list>

      <app-message-input
        [status]="(status$ | async)!"
        [users]="(users$ | async) ?? []">
      </app-message-input>
    </main>
  </div>

  <!-- DM panel -->
  @if ((activeDm$ | async); as activeDm) {
    <app-direct-message-panel
      [partner]="activeDm"
      [currentUser]="session.username"
      [messages]="getDmMessages(activeDm, (dmMessages$ | async) ?? {})"
      (send)="onSendDm($event, activeDm)"
      (closed)="closeDm()">
    </app-direct-message-panel>
  }

  <!-- Mention toasts -->
  @if (((mentions$ | async) ?? []).length > 0) {
    <div style="position:fixed;bottom:1.5rem;right:1rem;display:flex;flex-direction:column;gap:0.5rem;z-index:200;max-width:min(320px,calc(100vw - 2rem))">
      @for (m of (mentions$ | async) ?? []; track m.id) {
        <div style="background:var(--surface);border:1px solid #ff9944;border-radius:8px;padding:0.75rem 1rem;box-shadow:0 4px 20px rgba(0,0,0,0.4);font-size:0.82rem">
          <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:0.35rem">
            <span style="font-weight:700;color:#ff9944">&#64;mention in #{{ m.roomName }}</span>
            <button (click)="clearMention(m.id)" style="background:none;border:none;color:var(--muted);cursor:pointer;font-size:0.8rem">✕</button>
          </div>
          <div style="color:var(--text-dim);margin-bottom:0.4rem">
            <strong style="color:var(--text)">{{ m.username }}</strong>: {{ m.text.slice(0, 100) }}{{ m.text.length > 100 ? '…' : '' }}
          </div>
          <button (click)="handleSwitchRoom(m.roomId); clearMention(m.id)"
                  style="font-size:0.72rem;padding:0.2rem 0.6rem;border:1px solid #ff9944;border-radius:4px;background:none;color:#ff9944;cursor:pointer">
            Go to room →
          </button>
        </div>
      }
    </div>
  }

  <!-- Modals -->
  @if (modal === 'admin') {
    <app-admin-panel [token]="session.token" (closed)="modal = 'none'"></app-admin-panel>
  }
  @if (modal === 'changePassword') {
    <app-change-password-modal [token]="session.token" (closed)="modal = 'none'"></app-change-password-modal>
  }
}
